### ISSUE TITLE
Remove all references to Obaju e-commerce template

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#100]

**Comment by errordeveloper** [comment]
Seems it still shows up somehow in the HTML metadata somewhere. I've pasted a link in Slack and this is what showed up:
![](https://www.dropbox.com/s/3so2c1p6718f2q0/Screenshot%202016-07-20%2012.52.17.png?dl=1)

**Comment by idcrosby** [comment]
@errordeveloper can you verify the creation date for the images you are running? We haven't done a 'release' in over a month, so this is probably still running the old images. 
sidenote: probably time for us to do another release

**Comment by errordeveloper** [comment]
Just for the record, I've checked the HTML and this what appears in the front page:

```
<meta name="description" content="Obaju e-commerce template">
```

@idcrosby sure, that makes sense. I'm running whatever is on Docker Hub right now.

**Comment by idcrosby** [comment]
yup, that's old code, we will cut a new release

**Comment by errordeveloper** [comment]
Cool. Please close this.
