### ISSUE TITLE
Front-end is flakey

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#101]
The front-end crashes a lot. Whenever there is a url related error (404/500/etc.) it will crash.

**Comment by idcrosby** [comment]
Found/fixed a couple issues around this. @philwinder do you have any specific examples you remember?

**Comment by philwinder** [comment]
If any of the API calls result in a 500, it will crash. So, yeah,
everywhere. Kill one of the services, then click through the gui to
activate it and watch it crash. E.g. stop the login service, then try and
log in. It will crash.

**Comment by idcrosby** [comment]
found the (main) issue, we don't return after the 'callback(error)' in many places....

**Comment by idcrosby** [comment]
Think I fixed all of these, if this happens again, let me know
