### ISSUE TITLE
Catalogue database for catalogue service

### ISSUE THREAD

**Issue by idcrosby** [microservices-demo/microservices-demo#106]
Catalogue contents (socks) currently read from file. Not mutable.
- [ ] Investigate other sources of catalogue data. E.g. any Amazon data dumps?
- [ ] Create DB and insert sock data
- [ ] Save DB as Docker image, so data is immutable and doesn't need "insert data" scripts
- [ ] Hook up DB to catalogue service
- [ ] Making the DB schema flexible enough so we can remove the "Sock" data and replace with other data.

**Comment by philwinder** [comment]
Fixed in new catalogue service. See https://github.com/microservices-demo/catalogue.
