### ISSUE TITLE
Optimise build & images

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#128]
There's room for a significant reduction in the number of layers and size of images.

Create a common, minimal base image for each service type:
- [x] Node
- [x] Java + Spring

Build binaries and packages and add/copy/move them to the eventual target.
- [x] Copy GoKit services to Alpine\* binary
- We will use Alpine because we expect to want to add & use tools for tutorials

**Comment by rade** [comment]
Here are the current base images

```
./worker/Dockerfile:1:FROM golang:1.6-wheezy
./login/Dockerfile:1:FROM golang:1.6-wheezy
./payment/Dockerfile:1:FROM golang:1.6-alpine
./catalogue/Dockerfile:1:FROM golang:1.6-wheezy
./orders/Dockerfile:1:FROM java:openjdk-8-alpine
./shipping/Dockerfile:1:FROM java:openjdk-8-alpine
./accounts/Dockerfile:1:FROM java:openjdk-8-alpine
./queue-master/Dockerfile:1:FROM java:openjdk-8-alpine
./cart/Dockerfile:1:FROM java:openjdk-8-alpine
./load-test/Dockerfile:1:FROM python:2.7-wheezy
./example/Dockerfile:1:FROM python:2.7
./edge-router/Dockerfile:1:FROM nginx:1.11.0-alpine
./front-end/Dockerfile:1:FROM node:4.4.4
```

A couple of things stick out that should be fixable quickly:
- the three golang:1.6-wheezy images should be replaced with golang:1.6-alpine
- the python:2.7-wheezy and python:2.7 should be replaced with python:2.7-alpine

The node image is a killer since it's based on Debian and there is [no obvious alternative](https://hub.docker.com/_/node/)

I don't understand why we have golang images; surely we should be building static binaries and stick them in 'scratch' images, or, for easy of debugging, plain alpine images.

**Comment by rade** [comment]
From a clean machine, on 80Mbps fibre:

```
$ time docker-compose up -d
...
real    4m52.174s
user    0m2.876s
sys 0m0.404s
```

ouch

```
$ docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
mongo                          latest              7f09d45df511        43 hours ago        336.1 MB
weaveworksdemos/load-test      latest              dada39e52ad6        3 days ago          551.9 MB
rabbitmq                       3                   07ad51c82a29        6 days ago          189.9 MB
weaveworksdemos/edge-router    latest              a385e0d393c6        4 weeks ago         60.62 MB
weaveworksdemos/shipping       latest              a5b5459b7e34        4 weeks ago         161.4 MB
weaveworksdemos/queue-master   latest              b77cc45d6c79        4 weeks ago         169.3 MB
weaveworksdemos/payment        latest              0dda059d9003        4 weeks ago         289.8 MB
weaveworksdemos/orders         latest              98229c9d1ad1        4 weeks ago         221.9 MB
weaveworksdemos/login          latest              3ee5178e48eb        4 weeks ago         290.1 MB
weaveworksdemos/front-end      latest              3f86d7d004bc        4 weeks ago         677.1 MB
weaveworksdemos/catalogue      latest              55de568488d4        4 weeks ago         669.7 MB
weaveworksdemos/cart           latest              c28e4e194400        4 weeks ago         183.1 MB
weaveworksdemos/accounts       latest              0c6a308a2c81        4 weeks ago         163.9 MB
```

(though there is some sharing of layers, so it's not quite as bad as it looks)

**Comment by rade** [comment]
I tried to change

```
./load-test/Dockerfile:1:FROM python:2.7-wheezy
```

to `python:2.7-alpine` but that fails because apparently the build needs gcc for pyzmq:

```
  ...
  Failed building wheel for pyzmq
  ...
  running configure
  pkg-config not found
  {'libraries': ['zmq'], 'extra_link_args': [], 'runtime_library_dirs': [], 'library_dirs': [], 'include_dirs': []}
  gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -c build/temp.linux-x86_64-2.7/scratch/check_sys_un.c -o build/temp.linux-x86_64-2.7/scratch/check_sys_un.o
  unable to execute 'gcc': No such file or directory
  Warning: No sys/un.h, IPC_PATH_MAX_LEN will be undefined: command 'gcc' failed with exit status 1
```

**Comment by rade** [comment]
```
./example/Dockerfile:1:FROM python:2.7
```

That isn't actually used in the demo compose.

**Comment by rade** [comment]
I tried to change

```
./catalogue/Dockerfile:1:FROM golang:1.6-wheezy
```

to `golang:1.6-alpine` but that fails because apparently (and not unreasonably) it needs git:

```
...
Step 3 : RUN go get github.com/gorilla/mux github.com/go-kit/kit/...
 ---> Running in 033470c8b093
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/gorilla/mux: exec: "git": executable file not found in $PATH
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/go-kit/kit/...: exec: "git": executable file not found in $PATH
The command '/bin/sh -c go get github.com/gorilla/mux github.com/go-kit/kit/...' returned a non-zero code: 1
...
```

The same applies to

```
./worker/Dockerfile:1:FROM golang:1.6-wheezy
./login/Dockerfile:1:FROM golang:1.6-wheezy
```

**Comment by rade** [comment]
So simply changing the base images isn't possible, at least not easily.

Which means we have to switch to the proper way of constructing images, i.e. as noted above "Build binaries and packages and add/copy/move them to the eventual target."

**Comment by BenHall** [comment]
With Go containers we have a "builder" container which generates the statically linked Go binary. A second Image is used for deploying it based on scratch. 

This allows for the builder to have all the required tooling, such as Git, but the actual release be extremely small. 

Here is an example - https://github.com/katacoda/golang-http-server

**Comment by idcrosby** [comment]
thanks, @BenHall was able to shrink our Go images significantly with this pattern (they are now under 9MB).

Looking into the Java and Node images now.

**Comment by BenHall** [comment]
Great news! I can't remember if there is an official Java alpine image, but I know there isn't one for node. 

We built one at https://github.com/OcelotUproar/alpine-node and Java is https://github.com/OcelotUproar/alpine-java

**Comment by idcrosby** [comment]
Thanks, I found this one: https://hub.docker.com/r/mhart/alpine-node/ and was able to get it down to 79 MB.  Just noticed you reference mhart's image. Any reason you built your own instead of using that one?

**Comment by BenHall** [comment]
Ahh yes, I forgot we based it on that. I imagine it was so we can controlled our upstream dependencies. I like to know how to build the images, just incase new versions don't appear :)

**Comment by idcrosby** [comment]
https://github.com/weaveworks/microservices-demo/pull/158

Have left the java images since they are already using alpine and won't get much smaller. Also left the python/load-test image as is (for now) since it's not part of the actual application.

**Comment by idcrosby** [comment]
A bit better now, but still not great

```
$ time docker-compose up -d
...
real    3m45.740s
user    0m2.056s
sys 0m0.385s
```

**Comment by pidster** [comment]
See also: https://github.com/weaveworks/microservices-demo/issues/53
