### ISSUE TITLE
Make deploy README's consistent

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#129]
Each deploy README should be written in a consistent way, containing (wherever possible) similar steps and instructions.
1. State deployment platform & link to page, docs
2. State deployment method (e.g. declarative file format)
3. Specify instructions for deployment
4. State expected outcome, method to check success

**Comment by nustiueudinastea** [comment]
the documentation is quite consistent at the moment. If you take a look now do you find something that's not satisfactory?
