### ISSUE TITLE
Add CloudFormation one-click deploy to ECS README

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#133]
There's a one-click deployment mechanism for CloudFormation. We should add that to the README.

**Comment by errordeveloper** [comment]
I am not quite sure we really need the shell-based version. I'm happy to help with this. I'd start by copying one of the existing templates and replacing [task and service definitions](https://github.com/weaveworks/integrations/blob/373137c9cdb7622eac567a63db4f0befb2a29d91/aws/ecs/cloudformation-identiorca.json#L175-L235), all that needs to change is attribute capitalisation. The integrations repo [is configured](https://github.com/weaveworks/integrations/blob/373137c9cdb7622eac567a63db4f0befb2a29d91/.travis.yml) to test and publish templates to S3.

**Comment by errordeveloper** [comment]
For the record, we also have https://github.com/weaveworks/integrations/issues/86, but simply copying the template will be fine for now. Perhaps we could discuss whether we really need all those different forked templates ([`integrations/aws/ecs/cloudformation*.json`](https://github.com/weaveworks/integrations/tree/373137c9cdb7622eac567a63db4f0befb2a29d91/aws/ecs)) with ad-hoc demo apps, once we have this app. We could just say that this app is the only one we will feature.

**Comment by errordeveloper** [comment]
cc https://github.com/weaveworks/integrations/issues/99

**Comment by pidster** [comment]
I'm OK with the README starting with "click here", then explaining the CLI version too.
Horses for courses.
