### ISSUE TITLE
light-weight demo

### ISSUE THREAD

**Issue by rade** [microservices-demo/microservices-demo#135]
Even with the best possible outcome of #128, the images are still going to be big. After all we are using java, nginx, rabbitmq, etc, etc.

So I assembled a [simulation of weavesock](https://github.com/rade/dummi#weavesock-demo). This has the same structure as the real thing but only requires a single 9MB image. The whole thing downloads and launches from a completely blank (zero images) machine in 6 seconds!

Here is a screen shot of what you get:
![screenshot_2016-07-17_10-14-48](https://cloud.githubusercontent.com/assets/109109/16900712/9fcf10aa-4c24-11e6-8999-1c5acc5c9d46.png)

And here's the compose output, which looks rather prettier than the real demo:
![screenshot_2016-07-17_10-11-55](https://cloud.githubusercontent.com/assets/109109/16900718/ba5954b2-4c24-11e6-9d08-c86a1f677106.png)

The thing to do here then is to
- [ ] move the code into this repo
- [ ] switch image name to something under weaveworksdemos
- [ ] ditch the primary docker-compose.yml and move docker-compose-weavesock.yml in its pace
- [ ] improve the suggested steps in the README.md so that they become more of a guided tour of Scope
- [ ] switch the instructions on the Weave Cloud org page to point at this rather than the main docker-only demo

All assuming that we think this is a good idea :) @pidster

**Comment by rade** [comment]
The other advantage of this over the real demo app is that it it consumes far fewer resources on the host machine, and does not need a load generator.

**Comment by pidster** [comment]
This is great.
The code could live under a top-level directory called `/micro-sock/`.
The compose file should live under `deploy/micro-sock/docker-compose.yml`.

**Comment by rade** [comment]
Another improvement that came up in discussion is that we could add an http endpoint to the edge_router that serves some static html+images with some of the contents of the README.

This will bloat the download somewhat though since it really needs to be a different executable - wouldn't want to clutter the exceedingly simple dummi/main.go with an http handler. Entails some refactoring too since that exe has to serve http _and_ do the dummi/main.go stuff.

**Comment by philwinder** [comment]
@rade Where is the code for this? I'd recommend having it in a separate repo under MD/. It's confusing enough already.

**Comment by rade** [comment]
> Where is the code for this?

See link in first comment.

**Comment by nustiueudinastea** [comment]
This project has been imported under the Microservices Demo organisation (https://github.com/microservices-demo/micro-sock). Also added a documentation page on how to use it to quickly launch a Docker Compose + Weave Scope to display the simulated Sock Shop topology on Weave Cloud: https://microservices-demo.github.io/microservices-demo/deployment/micro-sock.html.
