### ISSUE TITLE
Use Amazon ELB instead of edge-router container

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#145]
The edge-router container is redundant in ECS - a configuration for ELB would be better.

**Comment by errordeveloper** [comment]
CloudFormation template (https://github.com/weaveworks/integrations/pull/100) already has ELB. Should I simply remove edge-router and go straight to front-end's port 80?

**Comment by errordeveloper** [comment]
Ok, it's `front-end:8079`.

**Comment by philwinder** [comment]
Fixed in the above ping.
