### ISSUE TITLE
Move code for 'Sock Shop' into 'sockshop' sub-directory.

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#171]
In an effort to accommodate additional demos and make it easier to understand what's in this repo, we will tidy up & move things around.

The top-level directories will be:

```
/demo
/deploy
/docs
/install
/load-test
/micro-sockshop
/sockshop
/docs
```

**Comment by philwinder** [comment]
Do we still need the `/demo` dir?
Also, I'm adding a `./testing` dir for the test pipeline scripts. I'd like that to be a root level dir, since some of the test (e.g. deployment tests) are not just testing the sockshop.
