### ISSUE TITLE
Technology agnostic method of auto-generating API documentation

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#181]
For example: Simple option would be to add a link in the readme to the api-spec to the swagger UI:
http://editor.swagger.io/#/?import=https://rawgithubusercontent.com/microservices-demo/payment/master/api-spec/payment.json

**Comment by jasonrichardsmith** [comment]
How about Swagger UI instead?

http://petstore.swagger.io/?url=https://raw.githubusercontent.com/microservices-demo/payment/master/api-spec/payment.json#/default

You want this linked in README files?

**Comment by vlal-zz** [comment]
Done
