### ISSUE TITLE
Add tooling to generate Open API (swagger) spec

### ISSUE THREAD

**Issue by idcrosby** [microservices-demo/microservices-demo#192]
Annotations should allow us to automatically generate/update our swagger spec as part of the build. See:

https://goswagger.io/generate/spec/

https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X

**Comment by sashkachan** [comment]
I think this should go along with API versioning, which we don't currently have.
I assume there will be situations where a new services or new development will require additions to an API spec and implementation, so we'll have to make sure we support multiple versions are available.
