### ISSUE TITLE
Swap out nginx as the edge-router for a proxy that allows dynamic dns lookups

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#220]
See #185.

Nginx wouldn't query the dns dynamically. It only queries once upon startup. There are a few supposed hacks to get it to work, but I found it to be super flakey. It would work a few times then 502, when the service was still there and accessible.

Look at alternatives.

If we don't do this, then the dns lookup for the front-end is only performed once when nginx starts. If the front-end dies and/or starts on another ip address, it will 502. What's more, if we try and start new services, I don't think the front end will ever talk to the new services, because it's still stuck using the old dns entry.

**Comment by pidster** [comment]
See also: https://github.com/microservices-demo/microservices-demo/issues/233
I think there's a solution that avoids replacing NGINX entirely.

**Comment by nustiueudinastea** [comment]
@philwinder @pidster should I just go ahead and change to a different proxy or we are still waiting for NGINX?

**Comment by pidster** [comment]
We are not waiting any longer.

**Comment by nustiueudinastea** [comment]
Problem fixed by replacing nginx with traefik. I also tested it by taking down the front-end container and bringing up with a new ip. Traefiks picks it up and things continue to work from then on.
