### ISSUE TITLE
[WIP] Decompose projects

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#223]
Decompose this project into various individual repositories.
- [x] Extract front-end
- [x] Extract queue-master
- [x] Extract login
- [x] Extract accounts
- [x] Extract cart
- [x] Extract edge-router
- [x] Extract catalogue
- [x] Extract orders
- [x] Extract payment
- [x] Extract shipping
- [x] Extract worker
- [ ] Extract load-test
- [ ] Rename this repo to `deployment-configs`, retaining the `deploy` dir.

**Comment by sashkachan** [comment]
~~Nearly all of this is done.~~
~~Note sure about the last one.~~
~~The repo will also hold container and API tests as well as deployment configs.~~
~~I'd say we stick to the name, as it will probably will contain a high level overview of the project.~~

@idcrosby @jasonrichardsmith @philwinder @mongrelion  Are we ready to rename the repo? #278

**Comment by philwinder** [comment]
I'm not sure about the rename. We need a landing page somewhere, and currently this repo is that landing page. Wait for @pidster
