### ISSUE TITLE
Ability to register and add new users

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#229]

**Comment by jasonrichardsmith** [comment]
This is built into the user service.
The flow can be seen in the load test script
https://github.com/microservices-demo/load-test/blob/master/locustfile.py#L81

The flow is register -> returns user id -> create address or card with user id -> return address id.
Address or card is now attached to user, the user id can be used to create as many address and cards as necessary.

This just needs to be added to the front end.  I will check with others but will probably pick this up on Sep 1.

**Comment by jasonrichardsmith** [comment]
I am starting work on this

**Comment by philwinder** [comment]
Fixed in microservices-demo/front-end#13

**Comment by vlal-zz** [comment]
@jasonrichardsmith @philwinder 
It seems registering isn't fully complete. Orders fail to submit because address and card for the newly registered user is missing. I'll add an option during checkout for this.
