### ISSUE TITLE
Add imagelayers.io badges.

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#251]

**Comment by jasonrichardsmith** [comment]
having issues with imagelayersio at this moment
![imagelayersio](https://cloud.githubusercontent.com/assets/1245554/18079761/a55a5878-6e92-11e6-87e3-7dee7809cac0.png)

**Comment by jasonrichardsmith** [comment]
Already reported here
https://github.com/CenturyLinkLabs/imagelayers/issues/29

**Comment by pidster** [comment]
Might be the new layer format.

Closing this one, we'll just do the micro badger thing.
