### ISSUE TITLE
Fix user endpoint API spec

### ISSUE THREAD

**Issue by sashkachan** [microservices-demo/microservices-demo#266]
/login endpoint is specced to return an array, should be an instance of a user.
Review other issues with the spec.

**Comment by jasonrichardsmith** [comment]
@alex-glv I was going to fix this, should this still be open?

**Comment by sashkachan** [comment]
@jasonrichardsmith I closed the issue because it should be fixed under the user repo
https://github.com/microservices-demo/user/issues/4

**Comment by jasonrichardsmith** [comment]
@alex-glv  Ok, I can change on the user service.  I built this based on the login service, which returns a user.
https://github.com/microservices-demo/login/blob/master/service.go#L53
