### ISSUE TITLE
Travis build failing on master

### ISSUE THREAD

**Issue by jml** [microservices-demo/microservices-demo#274]
https://travis-ci.org/microservices-demo/microservices-demo/builds/153497695 failed, where I would have expected it to be green.

If I see a project that I'm thinking of trying out and its build is failing then I skip it for now and maybe maybe come back to it later.

**Comment by idcrosby** [comment]
Thanks @jml, build is resolved now. Project has been in some flux the past week. But your point is well taken we need to take more care in keeping the build healthy.
