### ISSUE TITLE
Bugs in deployment scripts for aws-ecs & Kubernetes 

### ISSUE THREAD

**Issue by deafRandom** [microservices-demo/microservices-demo#286]
Hi
I'm a big fan of your project and I want to use this opportunity to thank you for sharing it!

I noticed a minor bug in the aws-ecs script:
The [setup1-infra.sh](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/aws-ecs/scripts/setup1-infra.sh) script doesn't receive the SCOPE_AAS_PROBE_TOKEN from the invoking [setup.sh](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/aws-ecs/setup.sh) script. Hence, the services will never show up in Scope.
Another thing that I noticed: Your script requires jq. My first deployment attempt got stuck in the middle because I didn't have it installed. It would be very nice if you could add a check for the existence of jq before running any further steps in the script.

Kubernetes deployment:
I get stuck at the 'terraform get' step when I try to run your kubernetes deploy script. The [main.tf](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/terraform/main.tf) file refers to a github directory that doesn't exist anymore (According to [this github issue](https://github.com/kubernetes/kubernetes-anywhere/issues/192) they are working on putting it back up). I tried to run it anyway by using the github history, download the [archived files](https://github.com/kubernetes/kubernetes-anywhere/tree/bd6a907d8614c0d3457d29503dc7f407dafd10d3/phase1/aws-ec2-terraform) to my local machine and change the link in main.tf accordingly. However, I'm still running into the following error message:
"Error loading Terraform: Error downloading modules: module ubuntu_ami: Error loading .terraform/modules/bb7........./main.tf: Error reading config for output ami_id: parse error: syntax error".
Do you have any idea how I could fix that?
Thanks a lot!

**Comment by idcrosby** [comment]
Hi, thanks for logging these bugs. For the aws-ecs script I will make the changes you identified to the scripts (passing in Scope token, if available) and checking requirements (jq) at the start of the script.

For the Kubernetes deployment. The kubernetes-anywhere project which we had originally based this off of has gone through a large refactoring recently, hence the missing module.  We will need to update our documentation for installing a k8s cluster. In the mean time You could try using the official kubernetes documentation for setting up a cluster as we did for our staging env (https://github.com/microservices-demo/microservices-demo/blob/master/docs/create-staging-environment.md) or use minikube(https://github.com/kubernetes/minikube) if you are just looking to test it out locally/quickly.

I will update this ticket as the scripts/docs are updated.

**Comment by idcrosby** [comment]
@gavrie thoughts on the aws-ecs script issue?

**Comment by 2opremio** [comment]
Please use https://github.com/weaveworks/guides/tree/master/aws-ecs as a reference, for which service tokens work.

In fact, we should unify the code to avoid fixing bugs like this one twice.

**Comment by vlal-zz** [comment]
Fixed by #468 #438
