### ISSUE TITLE
Create minimal setup/deploy

### ISSUE THREAD

**Issue by idcrosby** [microservices-demo/microservices-demo#287]
no load test or worker, anything else we can remove?
goal is to have quick pull/up time for demo or workshop

**Comment by pidster** [comment]
We have a super simple mini-shop app, that simulates the network connections but doesn't actually run a real shop.

**Comment by nustiueudinastea** [comment]
@pidster is this still relevant? We have a very simple docker compose setup that gets you running in a jiffy.

**Comment by rade** [comment]
> in a jiffy

Do you have some data to back that up? e.g. starting from a blank docker (no images at all), how long does `docker-compose up` take?

**Comment by vlal-zz** [comment]
@nustiueudinastea I think this is a dupe of #135.

**Comment by nustiueudinastea** [comment]
@rade I timed the "docker-compose up" command on blank docker and it takes roughly 5 minutes and 30 seconds to have the application ready. I find that very reasonable for a piece of software with so many moving parts and complexity. But that is nowhere near the time it takes to start the application you specified in #135. I will close this in favour of issues #135 . We can continue the discussion there.
