### ISSUE TITLE
Integrate Weave Cloud with Staging deploy

### ISSUE THREAD

**Issue by idcrosby** [microservices-demo/microservices-demo#292]
Include scope in the staging environment and use weave cloud credentials to push scope probe data to weave cloud. See https://www.weave.works/guides/using-weave-scope-cloud-service-to-visualize-and-monitor-docker-containers/ for more information

**Comment by vlal-zz** [comment]
@pidster do we have a token we can use for this?

**Comment by pidster** [comment]
Yes. It's added to Travis as: $WEAVE_CLOUD_TOKEN

**Comment by vlal-zz** [comment]
Closing in favour of #440
