### ISSUE TITLE
ECS demo no longer works

### ISSUE THREAD

**Issue by lukemarsden** [microservices-demo/microservices-demo#296]
Launching cloudformation via https://github.com/microservices-demo/microservices-demo/tree/master/deploy/aws-ecs results in a socks shop that you can't log into.

cc @idcrosby

**Comment by deafRandom** [comment]
Same is true for the [kubernetes deployment](https://github.com/microservices-demo/microservices-demo/blob/master/docs/create-staging-environment.md).

**Comment by idcrosby** [comment]
fixed by adding new full.json definition, and updating the version in s3.  The s3 version (linked to by CF button) should be automatically updated (via Travis?) TODO

**Comment by errordeveloper** [comment]
@idcrosby the manifest in S3 is updated by Travis, but it leave is in https://github.com/weaveworks/integrations, we also have a to-do ticket around re-usability of CloudFormation manifests https://github.com/weaveworks/integrations/issues/86 (any input is welcome).

**Comment by errordeveloper** [comment]
@idcrosby why does [`full.json`](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/aws-ecs/task-definitions/full.json) live in a directory called `tasks-definitions`? And where did it get copied from? Please remove it from here and make a PR agains integrations repo, as it's setup with S3 credentials already, we also update AMI IDs there regularly. The file you want update is [`cloudformation-microservices-referrence-app.json`](https://github.com/weaveworks/integrations/blob/master/aws/ecs/cloudformation-microservices-referrence-app.json).

**Comment by idcrosby** [comment]
@errordeveloper this was added to support Luke's demo during Software Circus. Have removed it with this PR: https://github.com/microservices-demo/microservices-demo/pull/312

I will submit a PR against integrations to update it. We need some mechanism in place to ensure they remain in sync.

**Comment by errordeveloper** [comment]
@idcrosby yes, we need such a mechanism. Also, we have 3 (or more) different formats now, which really talk about the same thing. Any thoughts on how we could solve that without writing to much code? I am thinking that a simple set of templates with a Python (or whatever is your favourite scripting language today) should do the job. A bit more clever way would be to use Compose as a source, with some annotations to hint at target-specific setings, or may be a Python DSL like one below could be more convenient...

``` python
class Shop(Deployments):
    @service
    def cart(self):
         return {"image": "microservices-demo/cart:latest", "ports": [80], "name": "cart"}
```
