### ISSUE TITLE
environment variable not set

### ISSUE THREAD

**Issue by sebgoa** [microservices-demo/microservices-demo#302]
Hi, looking at your docker-compose file, every service sets the _reschedule_ environment variable to _on-node_failure_. Is that what you are trying to do ?

Because it is not get set in the running container. Docker-compose silently fails (yaml gets parsed properly).

that's because you should use an equal sign.

Instead of:

```
    environment:
      - reschedule:on-node-failure
```

we should have:

```
    environment:
      - reschedule=on-node-failure
```

Unless I misunderstand what this env is doing.

**Comment by idcrosby** [comment]
thanks @runseb, yes that was the desired behaviour. I will update the docker compose files
