### ISSUE TITLE
When filtering, size, paging and page sizing returns incorrect values.

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#31]
We get the total data size from the backend. When filtering, this is obviously wrong.

**Comment by jasonrichardsmith** [comment]
I can take this issue

**Comment by philwinder** [comment]
Thanks @jasonrichardsmith. Could you assign yourself?

**Comment by jasonrichardsmith** [comment]
I don't have permissions @philwinder

**Comment by philwinder** [comment]
Hmm. Won't let me add you either. Oh well. Thanks, testing now!

**Comment by philwinder** [comment]
@jasonrichardsmith It works great from the backend. But as part of this PR, could you go into the frontend and fix the pagination buttons and the "showing 6 of 3 products" text. Just some simple sanity checks. Below is an image of what I mean:
![screen shot 2016-06-17 at 09 14 18](https://cloud.githubusercontent.com/assets/8793723/16144655/562f8f44-346c-11e6-9fbd-a0fccdfa89bc.png)

Both of these errors are in `front-end/category.html`.

Thanks!

**Comment by jasonrichardsmith** [comment]
Sorry about that.  I will check over lunch

**Comment by jasonrichardsmith** [comment]
This pull request was updated.  I also added a fix to address the tags being empty.
@philwinder

**Comment by jasonrichardsmith** [comment]
@philwinder still problems with the js logic.  Will look at tomorrow.

**Comment by jasonrichardsmith** [comment]
should be fixed now.
@philwinder

**Comment by philwinder** [comment]
Thanks. Will take a look on Monday.
