### ISSUE TITLE
Rename swarm folders for clarity

### ISSUE THREAD

**Issue by amouat** [microservices-demo/microservices-demo#313]
Currently the instructions for running old-school Swarm exist in deploy/docker-swarm. The new swarm instructions exist in swarmkit.

This is confusing for new users (I just talked to one) who just see "swarm" and associate it with the 1.12 Docker Swarm mode. They don't even know what "swarmkit" is.

Can I suggest we rename "swarmkit" to "docker-swarm-mode" and "docker-swarm" to "docker-swarm-old-standalone"? I think the majority of readers will be more interested in the new tech rather than the old.

**Comment by pidster** [comment]
+1

**Comment by vlal-zz** [comment]
Old docker-swarm was removed, and new docker-swarm is the only one left
This was covered in this PR microservices-demo/microservices-demo#417
