### ISSUE TITLE
Swarm mode misunderstanding

### ISSUE THREAD

**Issue by amouat** [microservices-demo/microservices-demo#336]
I see the text for swarmkit says at the bottom:

 "This will spawn all the services composing weave-socks app and expose the application on 192.168.11.10:30000 Since the front-end is run in --mode global it will be available on all nodes."

It's not entirely true. The `--mode global` flag does indeed start a container on every node, but  it's actually the mesh routing which makes it available. Even if there was only a single container running (i.e. no `--mode global`) the mesh routing would ensure each node routed the port to the container, regardless of whether it was running on that node or not.

I think a better example would be to use `--replicas=2` to show some failover/load-balancing and drop `--mode global`. Also, I'm not sure why we don't explicitly list a published port rather than having swarm pick one (which defaults to 30000). I don't see why we don't use port 80.

(I'll submit a PR for this next week hopefully, but I don't have time now)

**Comment by vlal-zz** [comment]
Old docker-swarm was removed, and new docker-swarm is the only one left
This was covered in this PR microservices-demo/microservices-demo#417
