### ISSUE TITLE
PRs fail when from forks

### ISSUE THREAD

**Issue by idcrosby** [microservices-demo/microservices-demo#337]
We need to add a fork check to all services. If it is a fork, docker push and staging deployment. It's the bastion credentials it fails on.

**Comment by idcrosby** [comment]
fixed by https://github.com/microservices-demo/microservices-demo/pull/340 ?

**Comment by philwinder** [comment]
No, nothing to do with that. See https://github.com/microservices-demo/front-end/issues/17

Need to skip when building from a fork.

**Comment by vlal-zz** [comment]
Fixed by switching to flux
Ref https://github.com/microservices-demo/microservices-demo/issues/344
