### ISSUE TITLE
Auto scaling

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#342]
Autoscale all the things!
Depends on #343.

**Comment by nustiueudinastea** [comment]
@philwinder can you slightly expand on what you have in mind when you talk about scaling? I have tested the scaling of our k8s + AWS deployment and that works when I just use the k8s scale command. When you say autoscale, you mean automatically scale based on load or amounts of requests going to a service?

**Comment by jasonrichardsmith** [comment]
May be relevant
https://github.com/hjacobs/kube-aws-autoscaler/blob/master/README.rst

**Comment by nustiueudinastea** [comment]
@jasonrichardsmith  I am trying to use this (https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler) autoscaler, which is part of the k8s distribution. But it is quite under-documented and it's proving a pain to setup. If you think using this is a bad idea let me know.

**Comment by philwinder** [comment]
I was thinking more of autoscaling the services, not the clusters.

If using AWS, you can use autoscaling groups to scale the machines. But that seems a bit overkill in this case. `kubeadm` uses autoscaling groups out of the box, but I think Thijs went back to good ol' terraform. So unless he's done that in there, it won't be turned on.

Also, I'm sure there will be some issues when scaling certain services. E.g. scaling the DB's will be next to impossible without messing about with dbs. So I'd recommend sticking to something simple like the auto-scaling front-end, or catalogue to begin with.

**Comment by philwinder** [comment]
@nustiueudinastea Have a look at this for a stale, but working example: https://github.com/microservices-demo/microservices-demo/pull/305

**Comment by nustiueudinastea** [comment]
@philwinder Started working on the autoscaling of the cluster and indeed, its quite some work, because the terraform setup needs revamping, and you can't provision the nodes with terraform anymore, because they would be created by the autoscaling group. I will leave the cluster static and do the scaling only for the stateless services. I hope I can generate enough load to trigger a scale up event.

**Comment by philwinder** [comment]
Yes that's a good idea. In Adam's tests he was able to produce enough load with a simple parallel get. E.g.
```
seq 1000 | parallel -j 10 'curl frontend'
```
or using a tool of your choice.

**Comment by nustiueudinastea** [comment]
Autoscaling has been implemented on K8s, using horizontal pod autoscalers. If we want to do autoscaling for other deployments, we should open separate issues for that.
