### ISSUE TITLE
Check that all all services continue to operate when there are multiple versions of the service running

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#343]
A testing task. Manually start multiple instances of all the services to check they can handle autoscaling.

Also see #245

**Comment by nustiueudinastea** [comment]
@#245 has been fixed and I am now in the process of testing scaling for all other services

**Comment by nustiueudinastea** [comment]
I manually scaled all the non-db services to 3 replicas and checked that all the functionality of the web shop is working. Everything seems to be working correctly, including the ordering process.
