### ISSUE TITLE
Replace bastion ssh scripts with fluxy

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#344]
Speak to weave guys for more information

**Comment by vlal-zz** [comment]
- [x] Add flux to staging env #516 
- [x] Add private key to github repo 
- [x] modify .travis.yml across all services, removing deploy section 
microservices-demo/carts#19
microservices-demo/front-end#56
microservices-demo/orders#36
microservices-demo/queue-master#13
microservices-demo/shipping#16
microservices-demo/catalogue#23
microservices-demo/payment#19
microservices-demo/user#34
- [x] remove [deploy script](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/deploy.sh) #517
