### ISSUE TITLE
Need to create the Kubernetes namespace sock-shop

### ISSUE THREAD

**Issue by bboreham** [microservices-demo/microservices-demo#356]
#355 did not fix the issue, or indeed change things.

Using the original config, I get:

```
$ kubectl apply -f .
namespace "kube-system" configured
namespace "sock-shop" created
networkpolicy "front-end-access" created
networkpolicy "orders-access" created
networkpolicy "orders-db-access" created
networkpolicy "payment-access" created
networkpolicy "prism-access" created
networkpolicy "rabbitmq-access" created
networkpolicy "shipping-access" created
networkpolicy "user-access" created
networkpolicy "user-db-access" created
deployment "orders-db" created
service "orders-db" created
deployment "orders" created
service "orders" created
deployment "payment" created
service "payment" created
deployment "queue-master" created
service "queue-master" created
deployment "rabbitmq" created
service "rabbitmq" created
deployment "shipping" created
service "shipping" created
deployment "user-db" created
service "user-db" created
deployment "user" created
service "user" created
Error from server (NotFound): error when creating "cart-db-dep.yaml": namespaces "sock-shop" not found
...
```

Using the updated config from #355 , I get:

```
$ kubectl apply -f .
namespace "kube-system" configured
namespace "sock-shop" created
networkpolicy "front-end-access" created
networkpolicy "orders-access" created
networkpolicy "orders-db-access" created
networkpolicy "payment-access" created
networkpolicy "prism-access" created
networkpolicy "rabbitmq-access" created
networkpolicy "shipping-access" created
networkpolicy "user-access" created
networkpolicy "user-db-access" created
deployment "orders-db" created
service "orders-db" created
deployment "orders" created
service "orders" created
deployment "payment" created
service "payment" created
deployment "queue-master" created
service "queue-master" created
deployment "rabbitmq" created
service "rabbitmq" created
deployment "shipping" created
service "shipping" created
namespace "sock-shop" configured
deployment "user-db" created
service "user-db" created
deployment "user" created
service "user" created
Error from server (NotFound): error when creating "cart-db-dep.yaml": namespaces "sock-shop" not found
...
```

Perhaps there is some race condition.

**Comment by bboreham** [comment]
Interestingly, the illusion that `kubectl` is doing things in the right order is caused by it printing out all the success messages followed by all the failure messages.

**Comment by bboreham** [comment]
This one-liner gets it right (executed in `deployments/kubernetes/manifests`):

```
kubectl apply -f sock-shop-ns.yml -f .
```

**Comment by axsuul** [comment]
Interesting how it differs depending on environments. On my machine it executes just fine with simply

```
# kubectl apply -f .
```

**Comment by bboreham** [comment]
It will depend on the order of the files in your filesystem directory

**Comment by axsuul** [comment]
Would it be better perhaps to rely on a shell script here? Something like `apply-manifests.sh` with contents

```
kubectl apply -f manifests/sock-shop-ns.yml
kubectl apply -f manifests
```

**Comment by bboreham** [comment]
As a quick cut-n-paste to get going, I'm happier with the one-liner.

**Comment by axsuul** [comment]
Another proposal is to name the namespace file as `_sock-shop-ns.yml` so it appears first? 

Or `0_sock-shop-ns.yml`

**Comment by bboreham** [comment]
If it's sorting the names in order then I don't understand why we saw different behaviour; it should always fail.

**Comment by pidster** [comment]
The Kubernetes docs now specifically create the namespace first.
Alternatively, we can do it in a one liner like this: `kubectl apply -f manifests/sock-shop-ns.yml -f manifests`.

**Comment by pidster** [comment]
See also: https://github.com/microservices-demo/microservices-demo/issues/360

**Comment by nustiueudinastea** [comment]
@bboreham @pidster The instructions on the microservice-demo website now create the namespace first, like mentioned in one of the previous comments. Also, the [complete-demo.yaml](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml) manifest, which is a single file manifest based on the manifests directory, create the namespace first. 

I will close this issue but if you still have concerns please reopen.
