### ISSUE TITLE
Kubernetes instructions are out-of-date and no longer work

### ISSUE THREAD

**Issue by vlal-zz** [microservices-demo/microservices-demo#360]
Update the kubernetes instructions to create a working reproducible build.
Add a minikube deployment folder/instructions

**Comment by enxebre** [comment]
It'd be nice to build a helm chart for this

**Comment by pidster** [comment]
For clarity, the configuration in: https://github.com/microservices-demo/microservices-demo/tree/master/deploy/kubernetes is working. The documentation & instructions are the TODO here.

**Comment by philwinder** [comment]
Same as #286

**Comment by frankscholten** [comment]
Fixed by @nustiueudinastea. See minikube PR https://github.com/microservices-demo/microservices-demo/pull/464/files

K8s on AWS was tested and works.
