### ISSUE TITLE
Username and password get into request URL for index.html

### ISSUE THREAD

**Issue by adam-sandor** [microservices-demo/microservices-demo#361]
After login url parameters are added to the request URL for index.html.

<img width="554" alt="screen shot 2016-10-14 at 11 38 51" src="https://cloud.githubusercontent.com/assets/10675791/19383013/e11e363e-9202-11e6-9522-ede8949f3c9c.png">

**Comment by jasonrichardsmith** [comment]
I don't think we are doing this anymore, but I could be wrong.  The backend gets it as http auth parameters
https://github.com/microservices-demo/user/blob/master/api/transport.go#L125
