### ISSUE TITLE
AWS ECS cloudformation template fails after a few minutes and is rolled back

### ISSUE THREAD

**Issue by mjlodge** [microservices-demo/microservices-demo#365]
- Add labels appropriate to the issue 
- Describe the expected behaviour and the actual behaviour
- Describe steps to reproduce the problem

Expected behavior: use CF template to launch SockShop on ECS. SockShop will run until CF template is explicitly terminated.
Actual behavior: SockShop comes up and starts working, but then front-end container "did not stabilize" and entire CF template is rolled back.

Steps to reproduce: Deployed CF template to AWS Oregon region using 3x m4.large instances. Sock shop comes up. Ran load test container to send traffic to the sock-shop and can observe in Weave Cloud. Then SockShop disappears from Weave Cloud. Checking CF console shows the following error caused CF rollback:

14:19:46 UTC-0700   CREATE_FAILED   AWS::ECS::Service   FrontEndService Service arn:aws:ecs:us-west-2:376248598259:service/sockshop-ecs-FrontEndService-17JH4G3K9KWBM did not stabilize.

**Comment by moretea** [comment]
Can not reproduce this; the ecs deployment test works fine at the moment. It could be caused by this problem that we fixed. https://github.com/microservices-demo/front-end/commit/d715e7adeaae5a713d3984ce41e569608a1b1bbe
