### ISSUE TITLE
Staging broken

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#381]
Front-end is non-responsive.

Also see #348

**Comment by vlal-zz** [comment]
It seems to be working now but accessible in an odd way, you need to know the nodeport to access it. I imagine it should be accessible on port 80? 

Also there seems to be two staging docs floating around [here](https://github.com/microservices-demo/microservices-demo/blob/master/staging/README.md) and [here](https://github.com/microservices-demo/microservices-demo/blob/master/docs/internal-docs/create-staging-environment.md), perhaps they should be merged.

**Comment by moretea** [comment]
@vlal https://github.com/microservices-demo/microservices-demo/pull/398 solves this right? Please re-open if this is not the case.
