### ISSUE TITLE
complete-demo.yaml broken

### ISSUE THREAD

**Issue by lukemarsden** [microservices-demo/microservices-demo#390]
`deploy/kubernetes/complete-demo.yaml` for some reason the orders service doesn't come up

**Comment by idcrosby** [comment]
I just tested the file (locally with minikube), all services come up and all functionality is working. @lukemarsden  What issue did you see? Is the pod/container not starting?

**Comment by pidster** [comment]
@lukemarsden I see this too; I suspect it is resource problem - if there's other things running, I can't find proof yet though.

**Comment by pidster** [comment]
This also happens on a larger cluster, so I doubt it's a resource problem.

**Comment by idcrosby** [comment]
any details on what happens? Is it the pod which doesn't come up? What state is it in?

**Comment by pidster** [comment]
Service & deployment is there, but no pods.

**Comment by pidster** [comment]
This seems more stable now. @lukemarsden can you find time to try it please?

**Comment by frankscholten** [comment]
@pidster For the website documentation and the deploy docs we use the manifests under `deploy/kubernetes/manifests'. Should we also add docs and deploy docs for the complete manifest?

**Comment by pidster** [comment]
@frankscholten yes, please.

**Comment by nustiueudinastea** [comment]
this issues has been solved by https://github.com/microservices-demo/microservices-demo/pull/469
