### ISSUE TITLE
Incorrect path to cloudformation template for Shippable demo

### ISSUE THREAD

**Issue by ttrahan** [microservices-demo/microservices-demo#410]
The path to the cloudformation.json file for the Shippable demo is incorrect in docs/ecs-weave-shippable.md - it should direct user to ./deploy/aws-ecs-shippable, not ./deploy/aws-ecs

**Comment by pidster** [comment]
@ttrahan if you include a "Fixes $github_issue_url" in the PR, it auto-closes the associated issue.

**Comment by ttrahan** [comment]
@pidster ah, sorry about that. will remember to do so on future PRs.
