### ISSUE TITLE
Use a sensible default instance type for ECS

### ISSUE THREAD

**Issue by 2opremio** [microservices-demo/microservices-demo#413]
The current CF template for deploying in ECS [uses `t2.micro` instances](https://github.com/microservices-demo/microservices-demo/blob/a27c67fca8f5eb6a89ae5badcbc97c5dd98dca72/deploy/aws-ecs/cloudformation.json#L90). They are free, which is great but the Stack doesn't work with such small instances (it doesn't even finish deploying, providing a bad user experience).

In my experience, it only works when using at least 3 `m4.xlarge` instances. We should use a default which is verified to work and remove any smaller instances from the list (maybe adding a clarification on this on the side).

`m4.xlarge` instances are overkill for a demo but it seems that's the smallest you can pick to make it work. We should probably revisit whether we are being too resource intensive for a demo application, but that's a different topic.

Related: https://github.com/microservices-demo/microservices-demo/pull/412#issuecomment-260906964

**Comment by 2opremio** [comment]
To clarify this even further, I get errors like the following when using 3 instances smaller than `m4.xlarge`.

```
11:24:52 UTC+0100   CREATE_FAILED   AWS::ECS::Service   QueueMasterService  Resource creation cancelled
11:24:52 UTC+0100   CREATE_FAILED   AWS::ECS::Service   OrdersService   Service arn:aws:ecs:us-west-1:376248598259:service/Fons-SocksShop-OrdersService-1TJWCCKBDH0GL did not stabilize.
11:24:51 UTC+0100   CREATE_FAILED   AWS::ECS::Service   LoginService    Service arn:aws:ecs:us-west-1:376248598259:service/Fons-SocksShop-LoginService-1HJ0A1CMK3YH1 did not stabilize.
11:24:50 UTC+0100   CREATE_FAILED   AWS::ECS::Service   AccountsDBService   Service arn:aws:ecs:us-west-1:376248598259:service/Fons-SocksShop-AccountsDBService-DVL8N5OLWQZN did not stabilize.
```

#412 is an attempt to fix this but I managed to reproduce the problem even when using those changes.

Also, according to @errordeveloper this error seems to happen with `m4.xlarge` instances as well, but I haven't run into that yet. However, I have managed to reproduce failures in 4 occasions with smaller instances.

**Comment by errordeveloper** [comment]
No, I didn't mean to rule out larger instance types as such...

Now that I rethink this, it's probably just the case that this is more likely to happen with smaller instances.

I am not very sure if this could be to do with smaller instances not having enough resources to schedule, but it's very possible that larger instance startup all the services faster and somehow make the CloudFormation happy that way, while smaller ones are subject to some kind of timeouts. I still don't understand enough about the internals of CloudFormation to come up with a better explanation, but may be the case that this is an indirect effect of a bug (or limitation in design).

**Comment by bchav** [comment]
@errordeveloper: The last time that I tried to deploy this onto t2 micros, CFN never completed because it waits for ECS services to reach equilibrium, but the ECS service scheduler is unable to find sufficient resources to place all of the services. My suspicion is that 4x T2's run out of memory fairly quickly. IIRC many of the services here require 512/1024mb of ram.  

If you disable rollback when launching a CFN template, it makes it significantly easier to retroactively debug what happened- you can log into instances, etc. You can take a look at the "events" tab in ECS (or call the describe-service API) to find out why the ECS scheduler was never able to place the task.

**Comment by moretea** [comment]
The deployment script for ECS in the `deploy` folder use manual scripting to set up a ECS cluster. This has not failed on me yet. It [uses `t2.small` instances](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/aws-ecs/scripts/setup1-infra.sh#L157).

I could replace these manual scripts with the declarative cloud formation script and see what's going wrong.

**Comment by pidster** [comment]
Is there a limit on the number of `t2.small` instances that can be launched at the same time?
Could we just start 6, if there's an intermittent resource issue?

**Comment by 2opremio** [comment]
@moretea How many instances does it deploy?

@pidster Where did you get the 6 number from? Have you confirmed it to work?

**Comment by moretea** [comment]
It uses [three](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/aws-ecs/scripts/setup1-infra.sh#L161) `t2.small` instances

**Comment by 2opremio** [comment]
Interesting, I tried exactly those instances and that quantity and got the same problem with cloud formation.

**Comment by moretea** [comment]
I just redeployed this using the scripts in `/deploy`. Verified that all services work properly and stabilize, see screenshot below.

@2opremio could you verify that setting up using this script works properly?
![2016-11-18-14-11-09](https://cloud.githubusercontent.com/assets/99988/20431246/6a424ebc-ad99-11e6-8f0b-319786b9cf1a.png)

**Comment by moretea** [comment]
@2opremio do you use the .json definitions from `deploy/aws-ecs/task-definitions`? Could you elaborate on which settings you use?  Have you tried setting the `EcsInstanceType` to `t2.small`?

**Comment by 2opremio** [comment]
I just use the CF template from https://microservices-demo.github.io/microservices-demo/deployment/ecs.html (maybe it uses that task). I have tried 3 `t2.small` and 3 `m3.medium` it failed in both cases with the error I pasted above.

It only worked when using 3 `m4.xlarge`

**Comment by bchav** [comment]
Many of the task definitions in the CFN deployment specify 512mb for memory, but in the bash deploy scripts all tasks use 256mb. This is probably the difference.

**Comment by 2opremio** [comment]
Great catch Brandon. @ilya could you give that a try?

**Comment by errordeveloper** [comment]
@bchav thanks for the info, I didn't realise rollback can be disabled.

**Comment by errordeveloper** [comment]
@moretea @fons the thing is that limits set in the taskdef files used by bash implementation work initially, but break after you keep the app running for a while, as it starts to eat more memory.

**Comment by moretea** [comment]
OK, I've only played with the shop for 5-10 min by running the load test script.

**Comment by errordeveloper** [comment]
By the way, this is a dup of https://github.com/microservices-demo/microservices-demo/issues/146, but I'll close #146 cuase the conversation has developed here.

**Comment by errordeveloper** [comment]
@moretea that said, this was an issue a few month ago (around the time I've opened #146), I don't know what may have improved since. Let's chat on Slack to determine how to proceed 👍
