### ISSUE TITLE
ECS CloudFormation: the WeaveScope output shouldn't be loadbalanced

### ISSUE THREAD

**Issue by 2opremio** [microservices-demo/microservices-demo#416]
The WeaveScope output goes through an ELB:

<img width="1535" alt="screen shot 2016-11-17 at 12 42 47" src="https://cloud.githubusercontent.com/assets/2362916/20388076/794fc438-acc3-11e6-9a50-a5472b2240cb.png">

This is wrong since it leads to a split brain in the apps, affecting things like terminal spawning:

See: https://github.com/weaveworks/scope/issues/2016#issuecomment-261226026
Identical issue for the integrations repository: https://github.com/weaveworks/integrations/issues/115

**Comment by vlal-zz** [comment]
@2opremio @errordeveloper 
Based on the conversation in weaveworks/integrations#115 should WeaveScope be removed from the elb completely, or put behind a ELBv2?

**Comment by 2opremio** [comment]
There are a few options:

* Use an ELB (I don't know what ELBv2 is) with a single Scope App instance
* Output the IP or public DNS (which should be enabled in that case) of one App instances
* Output the IP of public DNS of all the App instances (the user would have to pick one of them)

**Comment by vlal-zz** [comment]
@2opremio
It seems ALB isn't a viable solution either. But we can't output a single instance from an autoscaling group either, atleast not in the cloudformation outputs.  The best we can do is probably provide a command line option along the lines of `aws ec2....`. Thoughts?

**Comment by vlal-zz** [comment]
@2opremio thoughts?

**Comment by errordeveloper** [comment]
I really think Weave Cloud should be the recommended option, it provides
the best UX.

**Comment by jasonrichardsmith** [comment]
If you want we can require Weave Cloud to deploy.  That will resolve the issue.

**Comment by nustiueudinastea** [comment]
Fixed by https://github.com/microservices-demo/microservices-demo/pull/596. The elbv2 (ALB) works as long as sticky sessions are configured.
