### ISSUE TITLE
Can't add to cart if I'm not logged in

### ISSUE THREAD

**Issue by lukemarsden** [microservices-demo/microservices-demo#439]
Steps to reproduce:
- Follow instructions at https://www.weave.works/guides/cloud-testdrive-part-1-setup-troubleshooting/
- Observe that without logging in, clicking "Add to cart" on any socks does not result in the number of items in the cart being incremented.

**Comment by vlal** [comment]
@lukemarsden There seems to be an issue with the link. Seem it can't load the katacoda properly?

**Comment by vlal-zz** [comment]
* It appears to be caused by katacoda running behind node.js and using the same name for the cookie that stores the session id. So there was a naming conflict and a new session id was always regenerated.
