### ISSUE TITLE
services only have one instance

### ISSUE THREAD

**Issue by rade** [microservices-demo/microservices-demo#441]
The K8s and ECS services only have one instance, as a result demos cannot really show off the abstraction you get when switching from containers/pods to services.

**Comment by nustiueudinastea** [comment]
@rade K8s has the option to scale a service manually quite easily by increasing the replica count. For example:

```
kubectl --namespace sock-shop scale --replicas=3 deployment/front-end
```

ECS supports something similar by changing the cloudformation stack definition ("DesiredCount"), and than updating the stack. 

I think it's not worth adding more service instances to the default deployment since it's so easy to do that manually, when needed. And in a demo scenario, it's very nice to show someone the transition from one to multiple instances of the same service, rather than having multiple from the beginning.

What's your take on this?

**Comment by rade** [comment]
Multiple instances from the start shows something more interesting by default. That is worthwhile.

**Comment by nustiueudinastea** [comment]
I can see the value but it does create some issues. We are using the same manifests for deploying k8s with minikube and on AWS. Sock Shop already requires a lot of memory to run and that can be a problem when running on a laptop using minikybe. If we double the default amount of services we will be looking at 8-10 gigs of memory required for the minikube vm and that will definitely make it harder for some people to run it.

The AWS deployment has enough resources to spare, so if you think that AWS has a big priority over minikube, than I can easily change the defaults.

**Comment by rade** [comment]
> Sock Shop already requires a lot of memory to run and that can be a problem when running on a laptop using minikybe.

This is something that is going to have to get addressed.

**Comment by jasonrichardsmith** [comment]
Relates to #135

**Comment by pidster** [comment]
We will increase the default task per service count in the ECS version for now.
The k8s staging environment can be set to run with more pods per service too, but it doesn't need to be changed on the defaults.

**Comment by nustiueudinastea** [comment]
The ECS instance count has been increased for all services that are not a database. Once the web shop is loaded up with requests via the load-test container and different browsers, everything  shows up connected in Weave Scope.

**Comment by rade** [comment]
> The k8s staging environment can be set to run with more pods per service too, 

This hasn't been done. -> re-opening.

**Comment by lukemarsden** [comment]
I guess we'll need a separate copy of all the yamls for the staging env versus the regular https://github.com/microservices-demo/microservices-demo/tree/master/deploy/kubernetes/manifests if we want to diverge the configurations between them

**Comment by pidster** [comment]
There is already separate copy. 

The staging env uses a clone of that repo so Flux can do deployments against it without conflicts in the public repo: [https://github.com/microservices-demo/flux-staging-deploy](https://github.com/microservices-demo/flux-staging-deploy)

I took the view at the time of creation that this was preferable, over having Flux do the version upgrades in public.

**Comment by lukemarsden** [comment]
ah, fine, so this is a trivial change. Thanks!

**Comment by jasonrichardsmith** [comment]
this was merged and deployed to sock shop.
