### ISSUE TITLE
make use of some AWS services

### ISSUE THREAD

**Issue by rade** [microservices-demo/microservices-demo#442]
It would be good if SockShop optionally made use of some AWS services, since many users will be running on AWS and hence it helps to show how the integration is done and how it is represented in various tools (e.g. Weave Scope renders AWS services distinctly from others).

**Comment by jasonrichardsmith** [comment]
I could easily provide a flag for the user service where it would use dynamo or simpledb instead of mongodb.  Is that something you would like to add? @rade

**Comment by rade** [comment]
maybe. @2opremio, what do you think?

**Comment by 2opremio** [comment]
> dynamo or simpledb

I am not familiar with the costs. I assume there is no free tier, but assuming they don't cost too much compared to the instances and that they can be easily deployed I would go for it.

Note that we have tested Scope's representation of external services for Dynamo but not for SimpleDB

**Comment by jasonrichardsmith** [comment]
SimpleDB is becoming the obscure step child anyway

**Comment by jasonrichardsmith** [comment]
@2opremio @rade 
Do we have a list of AWS services that Scope supports.  Some of these services are not very compatible with DynamoDB

**Comment by 2opremio** [comment]
It supports anything accessed through a subdomain in amazonaws.com (e.g.
dynamodb.us-east1.amazonaws.com, s3.amazonaws.com,
sqs.us-east1.amazonaws.com, instancename.id.us-east1.rds.amazonaws.com  ...)

**Comment by roberth** [comment]
I will start working on this (through CS). For testing, I will use https://hub.docker.com/r/deangiberson/aws-dynamodb-local/
This issue can be assigned to me.

**Comment by jasonrichardsmith** [comment]
@rade I integrated catalogue with RDS on ecs deployment.  Is that enough or would you like more services using AWS?

**Comment by rade** [comment]
What does it look like in Scope?

Would be good to hook up to more than one AWS service.

**Comment by jasonrichardsmith** [comment]
I will get a screen shot.

We can add more.

**Comment by jasonrichardsmith** [comment]
![catalogue-rds](https://cloud.githubusercontent.com/assets/1245554/22459779/3b67381c-e7a2-11e6-8081-1455b7319e0e.png)

Here is an image of catalogue RDS.  Sorry for the wait, but there was a problem with scope displaying RDS if it was in the same VPC.

**Comment by 2opremio** [comment]
👍

**Comment by 2opremio** [comment]
The problem @jasonrichardsmith  mentions is  https://github.com/weaveworks/scope/issues/2163

**Comment by jasonrichardsmith** [comment]
@rade 
Currently @roberth is working on porting "orders" to Dynamodb.  When that is complete that would add two services.  If that is adequate, I won't look at porting anymore services over to AWS.

**Comment by jasonrichardsmith** [comment]
@pidster @rade I am closing this ticket.  we have two services using AWS (RDS, DynamoDB).  If you feel we need more feel free to reopen.
