### ISSUE TITLE
Terraform destroy for Kube demo doesn't work

### ISSUE THREAD

**Issue by ttrahan** [microservices-demo/microservices-demo#451]
After following the Kube instructions to successfully set up Sock Shop running on a Kube cluster on AWS, running the provided command to destroy the infrastructure does not destroy any resources:

![image](https://cloud.githubusercontent.com/assets/4467650/20979132/685c4316-bc60-11e6-86b7-32cbbfada8de.png)

**Comment by vlal-zz** [comment]
Strangely I wasn't able to reproduce this. Perhaps it was a one-off issue. Do you mind trying once more and seeing if it happens again?

**Comment by vlal-zz** [comment]
If so, I'm introducing a cleanup script in another PR that manually cleans things up for situations like this. terraform can be fickle 😞

**Comment by frankscholten** [comment]
@ttrahan Is this still a problem?

**Comment by nustiueudinastea** [comment]
@ttrahan I can't reproduce this unfortunately. I will close this issue, but if you still have the problem and can add some details that could reproduce it please re-open.
