### ISSUE TITLE
Continued confusion over two different sets k8s manifests

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#457]
Background:
The `complete-demo.yml` file is for a one-liner install from a curl. The manifests folder was created to work better with flux.

We have the `complete-demo.yml` file and the files in the `manifests` folder. Which does a user use?

The content of the manifests are different too. For example, in the `complete-demo` it uses a load balancer. In the manifests it uses a node-port.

The duplication will cause bugs.

IMO I want to remove one of these. So either the flux-friendly deploy has to go, or the ability for a one-liner curl install has to go.

@errordeveloper @squaremo Any preferences? Ideas?

**Comment by pidster** [comment]
We can't remove the `complete-demo.yaml`, it is now referenced from the Kubernetes docs.
I do not want to remove the separate manifests, for other reasons.

Ensuring people understand which is which is a matter of having clear documentation.

**Comment by nustiueudinastea** [comment]
This has been solved, as agreed, by https://github.com/microservices-demo/microservices-demo/pull/469. I made a new complete-demo.yaml based the manifests in the manifests/ dir. Tested the new file and it deploys correctly. Also, added a notice in the README so people pay attention to update the complete-demo.yaml when they make modifications to the manifests.
