### ISSUE TITLE
k8s manifests-based deploy doesn't work with minikube

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#458]
The k8s-manifests-deploy version doesn't work with minikube because minikube starts the k8s-dashboard on port 30000. Hence, the selected nodeport on the edgerouter won't be able to bind to 30000.

Change the port to another number. Make it cool.

**Comment by frankscholten** [comment]
Fixed by https://github.com/microservices-demo/microservices-demo/pull/464
