### ISSUE TITLE
Minikube deploy_doc uses undefined phases

### ISSUE THREAD

**Issue by moretea** [microservices-demo/microservices-demo#489]
It's using undefined `deploy_doc` phases! 
See [this section](https://github.com/microservices-demo/deploy_doc#phases-in-a-deploydoc) of the documentation for which phases are supported (and why these are needed in the first place)

**Comment by vlal** [comment]
I think it makes more sense to merge minikube into the k8s docs, otherwise subsequent steps might get lost and it'll be harder to keep them in sync.

**Comment by vlal** [comment]
plus I don't think we can test minikube on travis or aws, but if we know the other k8s deploy doc works than we can be pretty sure minikube will
