### ISSUE TITLE
K8s terraform is region locked

### ISSUE THREAD

**Issue by jasonrichardsmith** [microservices-demo/microservices-demo#528]
The generated Pem file is not found in the terraform scripts because of hardcoded 'eu-west-1' values.

```
aws_instance.md-k8s-master: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'deploy-docs-k8s' does not exist
```

run the [instructions](https://github.com/microservices-demo/microservices-demo/blob/master/docs/deployment/kubernetes.md) with the region set to us-west-2.

**Comment by nustiueudinastea** [comment]
If you export the environment variables from the instructions before creating the key, the key will be created in the correct region. That should avoid the problem that you reported.

**Comment by jasonrichardsmith** [comment]
That is what I did.  It created the key correctly in the region I had set 'us-west-2'  but the rest of the scripts failed to load the key.  I exported eu-west-1, created a new key and ran terraform and everything worked.

**Comment by nustiueudinastea** [comment]
Ahh, understood! My bad, didn't pay attention to some of the details. Indeed there's a bit too much hard coding in the terraform scripts

**Comment by nustiueudinastea** [comment]
Fixed this issue in PR https://github.com/microservices-demo/microservices-demo/pull/542. Should be merged soon.

Keep in mind that there is still an issue with Terraform that prevents deployment to 'eu-west-2' (https://github.com/hashicorp/terraform/issues/10726). This is fixed and will make it in the next release of Terraform.

**Comment by nustiueudinastea** [comment]
The instructions now list yet another environment variable that needs to be set, which is used by Terraform to read the region.
