### ISSUE TITLE
microservices-demo/deploy/kubernetes/complete-demo.yaml refers to non-existing image

### ISSUE THREAD

**Issue by zzhaoy** [microservices-demo/microservices-demo#533]
- Add labels appropriate to the issue 

- Describe the expected behaviour and the actual behaviour
In microservices-demo/deploy/kubernetes/complete-demo.yaml, there's a deployment "catalogue-db" referring to "weaveworksdemos/catalogue-db:0.4.0" image in DockerHub, however, the image doesn't exists.  The latest image version is 0.3.0, rather than 0.4.0.  Hence creating app in K8s will fail.

- Describe steps to reproduce the problem
1. Run following command in a machine connects to a Kubernetes cluster:
kubectl create -n sock-shop -f "https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml?raw=true"
2. Run following command to check pod status:
kubectl get pods --namespace=sock-shop
3. It's seen pod "catalogue-db" is in "ImagePullBackOff" state:
NAME                            READY     STATUS             RESTARTS   AGE
cart-2733362716-h6nbs           1/1       Running            0          13s
cart-db-2053818980-4tn8c        1/1       Running            0          13s
catalogue-3179692907-3pcs4      1/1       Running            0          13s
catalogue-db-2384399944-vz54r   0/1       ImagePullBackOff   0          13s
front-end-2250085842-lddl0      1/1       Running            0          13s
orders-3145060556-6b754         1/1       Running            0          12s
orders-db-3277638702-v3s5l      1/1       Running            0          12s
payment-1126449479-d59xj        1/1       Running            0          12s
queue-master-1190579278-prlhq   1/1       Running            0          12s
rabbitmq-3472039365-zzfmh       1/1       Running            0          12s
shipping-595972932-gw32m        1/1       Running            0          11s
user-937712604-s7fl2            1/1       Running            0          11s
user-db-431019311-4k4nw         1/1       Running            0          11s
zipkin-1283702850-483hr         1/1       Running            0          11s
4. Visit the application frontend, no product item is listed as catalogue-db cannot be accessed.

**Comment by nustiueudinastea** [comment]
hey @zzhaoy, nice catch! I fixed the version in the k8s manifest and the PR should be merged in a bit.

**Comment by nustiueudinastea** [comment]
PR merged, should fix your problem. Thanks for reporting!

**Comment by zzhaoy** [comment]
verified in k8s and see products in frontend, BRAVO!

**Comment by nustiueudinastea** [comment]
awesome, happy that the deployment works
