### ISSUE TITLE
Sockshop GUI not appearing in browser

### ISSUE THREAD

**Issue by abuehrle** [microservices-demo/microservices-demo#544]
I am running ```docker-compose -f deploy/docker-compose/docker-compose.yml up -d```

The containers seem to come up, but the edge router does not, seems to be stuck in a reboot mode:  

```f08917e078e8        weaveworksdemos/edge-router    "nginx -g 'daemon off"   47 hours ago        Restarting (1) 32 seconds ago   0.0.0.0:80->80/tcp, 0.0.0.0:8080->8080/tcp, 443/tcp   dockercompose_edge-router_1```

GUI does not come up.

**Comment by nustiueudinastea** [comment]
Hi @abuehrle , I think we had a brief conversation on slack where I suggested that you clean your old images. Has that helped?

**Comment by abuehrle** [comment]
I will give that a try.  It sounds like the problem.  Thanks for your help. I think we can close this issue.

**Comment by TheLox95** [comment]
> Hi @abuehrle , I think we had a brief conversation on slack where I suggested that you clean your old images. Has that helped?

I have the same issue. What you mean by 'clean'?

**Comment by abuehrle** [comment]
@TheLox95 it's been awhile, but I think he meant that you delete any duplicate, older images on your drive.

**Comment by TheLox95** [comment]
@abuehrle Thanks! It is fixed, in my case was https://github.com/docker/for-win/issues/573

**Comment by abuehrle** [comment]
Glad to hear it!
