### ISSUE TITLE
Push docker images in CD style

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#553]
In order to work better with flux we should alter the way images are pushed.

This applies to every repo in the MD project.

**Background**
Flux monitors a docker registry for any new image. It will deploy the newest image in that repository.

**Current**
At the moment all services push docker images for all commits (from any branch), `snapshot` for any commit on master, `latest` for the most recent tagged version and `tag`.

**Proposal**
Push every:
- commit on master in the format `master-<shortSHA>` where SHA is the short 8 character SHA.
- Tag in the format `tag`
- `latest` for the most recent Tag

**Reasoning**
This will allow us to do continuous delivery (i.e. everything on master is automatically pushed) but also deliver stable tagged versions for users testing the deploys.

**Comment by pidster** [comment]
LGTM

**Comment by nustiueudinastea** [comment]
This has been implemented for all the services.
