### ISSUE TITLE
Front end service hangs sometimes on AWS deploy

### ISSUE THREAD

**Issue by jasonrichardsmith** [microservices-demo/microservices-demo#582]
Cloudformation does not always complete because all 3 tasks don't always come up.  Most times it reports 2 out of 3 tasks completed.
The socks shop still works.

Cloudformation screen
![frontendhang1](https://cloud.githubusercontent.com/assets/1245554/22458893/c2414962-e79e-11e6-928f-63f53bc42299.png)

ECS Clusters screen
![frontendhang2](https://cloud.githubusercontent.com/assets/1245554/22458918/c6a0a1ce-e79e-11e6-904f-b09146c7ac5e.png)

Cause is yet unknown.

**Comment by jasonrichardsmith** [comment]
This is related to not enough ec2 instances coming up, possibly.

**Comment by jasonrichardsmith** [comment]
With the larger and more numerous instances in the cluster, I can no longer reproduce.

Closing until we witness again.

**Comment by nustiueudinastea** [comment]
I have done several deployments, manual, and automated (Travis) and I can't reproduce this anymore. The 4 instances always come up and all the 4 desired front-ends come up as well. @jasonrichardsmith are you still doing anything on this issues? If not, I suggest closing it.
