### ISSUE TITLE
Release all services to test Flux deployment

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#584]
Tag & release each service to test Flux auto-deployment process.

Verify that running versions are subsequently correct.

**Comment by jasonrichardsmith** [comment]
blocked by #586

**Comment by nustiueudinastea** [comment]
blocked by https://github.com/weaveworks/flux/issues/424

**Comment by nustiueudinastea** [comment]
All services have been released and set to automatic deployment.
