### ISSUE TITLE
CPU maxes out on my instances after a day or so

### ISSUE THREAD

**Issue by abuehrle** [microservices-demo/microservices-demo#589]
I have kubernetes, and the sockshop running on three digital ocean hosts with the following specs: 

Ubuntu 16.04
2 core processor
4 gig memory
60gig 

I noticed since you added in Zipkin that the performance has degraded significantly.  After a day or so of running, the hosts get bogged down at 100%CPU and zipkin seems to be taking up most of the resources. 

<img width="658" alt="screen shot 2017-02-02 at 7 37 31 am" src="https://cloud.githubusercontent.com/assets/13420383/22552049/e5bdb7de-e91c-11e6-8879-23a0eda01d06.png">

**Comment by jasonrichardsmith** [comment]
I am reaching out to Adrian Cole about this.

**Comment by abuehrle** [comment]
Great.  I was just going to add that I am seeing this issue again on the bare metal server as well. I have this scenario up now for about two days, and one of the nodes is maxed out at 100%.  I can invite you to the instance if that helps.

**Comment by jasonrichardsmith** [comment]
No that is OK.  It may have something to do with using the in memory storage engine (not meant for production).  Just to see how they respond first.
https://gitter.im/openzipkin/zipkin

**Comment by jasonrichardsmith** [comment]
Comments from zipkin team on gitter.

@jasonrichardsmith neither of those files uses an external database. I would expect over time for zipkins built in in-memory database to perform worse
@adriancole does the in-memory database expire and delete any data?

Adrian Cole @adriancole 12:14
@devinsba there's nothing in the in-memory database that's sustainable
eventually GC spiral
we could change that

Brian Devins @devinsba 12:15
That's what I thought. It's likely what @jasonrichardsmith is seeing with 100% cpu after a while

**Comment by jasonrichardsmith** [comment]
closing adding issue #598
