### ISSUE TITLE
Refactor login service

### ISSUE THREAD

**Issue by idcrosby** [microservices-demo/microservices-demo#59]

**Comment by jasonrichardsmith** [comment]
I could take this ticket.  Do you have a plan on how you would want to refactor?

**Comment by idcrosby** [comment]
There is a branch already for this (refactor/login) but haven't merged it in as there is a problem reading response bodies. You are welcome to take a look at that, or refactor as you see fit.

**Comment by jasonrichardsmith** [comment]
You are referring to the register handler?  Login seems to work fine.

**Comment by idcrosby** [comment]
Yup, it's the register handler that wasn't quite working as I liked

**Comment by jasonrichardsmith** [comment]
I think GO closes the resp body when the Location header is set.  Not sure.
Still having the same issue with the resp body, but I am just going to follow with GET request for now.
https://github.com/golang/go/issues/10069

Login has been rewritten with JWT in the header.
I also ditched the user files and just created salted passwords, and added it to the accounts package.

**Comment by philwinder** [comment]
Fixed by #103
