### ISSUE TITLE
Several containers have restarted frequently over the last six days

### ISSUE THREAD

**Issue by abuehrle** [microservices-demo/microservices-demo#609]
Kubernetes running in Ubuntu 16.04 on bare metal

The sample has been up and running for six days, but today I noticed the number of restarts on several containers: 

```
NAMESPACE     NAME                                            READY     STATUS    RESTARTS   AGE       IP              NODE
sock-shop    catalogue-3244713806-pstdq                      0/1       Running   626        6d        192.168.192.2   kube-node-2.local.lan
sock-shop     payment-1025926443-vbrwj                        1/1       Running   628        6d        192.168.192.4   kube-node-2.local.lan
sock-shop     user-99712959-k4v3p                             0/1       Running   641        6d        192.168.64.7    kube-node-1.local.lan
```

**Comment by nustiueudinastea** [comment]
@abuehrle could you look at the logs for one of the pods that restarts, and maybe post it here as well if there is something interesting? Looking at our staging environment that has the latest containers which are running for several weeks, I can't see anything out of the ordinary.

**Comment by abuehrle** [comment]
Here's some log information: 

User container logs shows this: 

```
131 tracer=Zipkin err="Post http://zipkin:9411/api/v1/spans: net/http: request c
anceled (Client.Timeout exceeded while awaiting headers)"
```

How do I get the logs from a pod?  I've tried: 

`kubectl logs -f user-99712959-k4v3p` 

but it just returns pod not found - likewise for all pods running.

**Comment by abuehrle** [comment]
@nustiueudinastea I will redeploy the app to Digital Ocean and leave it running for awhile to see if we still see this behaviour. I redeployed the app in Packet.net, and it looks like there have been a lot of updates.

**Comment by nustiueudinastea** [comment]
@abuehrle you are deploying to a single machine? If yes, please have 6-8 GB of memory available. Not sure if that's the issue, but I have seen similar problems when my test VM had lower memory allocated.

**Comment by abuehrle** [comment]
Packet.net has 8 gig on each of the three hosts.  I can experiment more freely on Digital Ocean. On the packet hosts I am a guest working on a blog post for them (with free time) and can't take up their hosts for too much longer.

**Comment by nustiueudinastea** [comment]
Than we can definitely exclude the memory problem.

**Comment by nustiueudinastea** [comment]
Hey @abuehrle, how's it going with the new k8s deployment? Still having issues?

**Comment by abuehrle** [comment]
I am not seeing those restarts after running for two days.

**Comment by nustiueudinastea** [comment]
Ok, than I will close this issue. If you notice the problem again we just re-open it and look closer at the problem.
