### ISSUE TITLE
Add Cloudwatch Logging

### ISSUE THREAD

**Issue by jasonrichardsmith** [microservices-demo/microservices-demo#613]

**Comment by jasonrichardsmith** [comment]
I added the logs to Cloudwatch for the aws-ecs deployment.  This was utilizing the Docker logs driver.  I could do this because each container was invoked individually.  With the k8s deployment I can utilize the docker logs driver to send to cloudwatch, but because I cannot invoke individual flags to execute through k8s, I cannot pass the log name for each service.  So the logs go into Cloudwatch but are identified by the container ID which makes searching the logs pointless.  I started working on the next option, which is to use the log agent.  This will require a little more configuration, and does pose a few problems.  As far as I can tell the agent will have to be configured for all services on every node in the cluster, even though the said service may not be running on the node.  I am not sure if this will cause issues the agent.  I am still investigating other options as well.

**Comment by nustiueudinastea** [comment]
@jasonrichardsmith do we really need to add the k8s logs to cloudwatch? I find it's a lot of work for not much gain. For ECS it's more important because it's harder to extract the logs from the containers, but with K8s it's easier with a correctly configured kubectl. I would close this if it's already implemented for ECS.

**Comment by jasonrichardsmith** [comment]
@pidster requested this I think for more detailed feedback on staging performance and problems.  Is that correct Stewart?

**Comment by jasonrichardsmith** [comment]
If we are going to put the ELK stack on Staging, this probably can be closed.
