### ISSUE TITLE
prometheus instrumentation on front-end

### ISSUE THREAD

**Issue by lukemarsden** [microservices-demo/microservices-demo#632]
I would like to be able to demonstrate prometheus metrics for the front-end. In particular, latency to the different microservices that it connects to.

Relates to https://github.com/microservices-demo/microservices-demo/issues/422

**Comment by lukemarsden** [comment]
Let's start with basic RED (request rates, error rates, latency) metrics for requests to the frontend and perhaps the requests that it makes to its backend services.

**Comment by nustiueudinastea** [comment]
@lukemarsden cool, looking into that at the moment.

**Comment by philwinder** [comment]
@lukemarsden Just checking requirements
>  the requests that it makes to its backend services

All the backend services have (in one form or another that we will improve shortly) metrics in prom. I can appreciate that having a duplicate metric that measures the latency from the catalogue service  (for example) from the front-end, which would basically be the standard catalouge latency + network overhead.

This would highlight any network specific issues that could occur between services.

But, considering that the likelihood of that occuring is very low, it would be simpler to keep metrics contained to their own service. I.e. front-end would only measure front-end latencies. This would cut down the number of required metrics.

Am I correct in saying this is what you wanted? Or did you not know that the other services already have metrics?
