### ISSUE TITLE
Update Weave Net versions to 1.9.3

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#645]
Weave Net 1.9.3 has been released.

Update all configs referring to Weave Net, to 1.9.3.

**Comment by nustiueudinastea** [comment]
I went through all the deployments and in the instances that we deploy Weave Net, we download it ad-hoc from an online locations. Example (https://git.io/weave). 

Staging is already running 1.9.3. 

If you have some other instance in mind, which I have missed but needs changing, let me know.
