### ISSUE TITLE
Start persistent load test / user simulator in staging

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo#646]
Run the load-test container against staging, at a low level, with enough requests to fully test all application paths.

**Comment by rade** [comment]
To be clear, the objective here is for scope to show the sockshop in all its glory - all components that can connect to each other should show as connected. Without putting much load on the machines.

And IMO this should happen by default for anybody deploying it. So not just staging.

As a byproduct this should also produce a nice stream of metrics, once we have RED metrics for all the services. (out of scope for this issue)

Ideally the load gen would live in a different namespace, so it doesn't clutter the view. But this could be done as a follow-up.

**Comment by jasonrichardsmith** [comment]
make load test more steady, with little downtime.

**Comment by jasonrichardsmith** [comment]
ensure load-test is in it's own namespace

**Comment by vlal-zz** [comment]
Done #671
