### ISSUE TITLE
Remove Zipkin from Docker Compose

### ISSUE THREAD

**Issue by jasonrichardsmith** [microservices-demo/microservices-demo#661]
Remove zipkin from both Docker Compose deployments

**Comment by lukemarsden** [comment]
Rationale for this is:
- sock shop should be as slim as possible in "run on your laptop" scenarios, which probably correspond with docker compose (generally)
- sock shop should be fully featured in Kubernetes environments, where at least people can choose to apply or delete specific bits of yaml

**Comment by jasonrichardsmith** [comment]
closed in #708
