### ISSUE TITLE
Java/Spring-boot services require way too much ram

### ISSUE THREAD

**Issue by philwinder** [microservices-demo/microservices-demo#666]
The java services require 1.4, 1.3 and 1.1 GB of RAM each.

Reduce the need for so much ram.

- [x] Docker Compose
- [x] Kubernetes manifests
- [x] Mesos
- [x] Nomad

**Comment by pidster** [comment]
There's no heap constraints applied, so it's probably grabbing as much as it can.

**Comment by pidster** [comment]
The configuration changes for Docker & Kubernetes look like they're working pretty well. The following can be applied to the other deployments:

    JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
