### ISSUE TITLE
Installation and deployment

### ISSUE THREAD

**Issue by Krishnananad** [microservices-demo/microservices-demo#675]
I am quite new to this space. Can someone please suggest me on how to deploy and use this demo application in windows platform? As I am new to microservices, it will be really helpful if someone could provide me a detailed instruction if possible. Please let me know if I need to provide any further information.

Thanks in advance.

**Comment by pidster** [comment]
Hi @Krishnananad GitHub issues are not really the best place to provide help of the sort you're asking for.

Having said that, I would suggest that you try installing Docker on your Windows machine, and then following the instructions for running Sock Shop using Docker Compose, here: https://microservices-demo.github.io/microservices-demo/deployment/docker-compose.html
