### ISSUE TITLE
Redundant Docker files? Or intentional?

### ISSUE THREAD

**Issue by rberlind** [microservices-demo/microservices-demo#687]
It seems that some of the repositories have redundant but different Dockerfile files.  Is this intentional?  For instance, carts has https://github.com/microservices-demo/carts/blob/master/Dockerfile and https://github.com/microservices-demo/carts/blob/master/docker/carts/Dockerfile which are quite different.

Is the top-level one meant for developers making modifications to the code while the nested one is meant for publishing to Docker Hub?  If so, why don't all repositories have a top-level Dockerfile? For instance, orders does not have one.

Thanks,
Roger Berlind

**Comment by jasonrichardsmith** [comment]
@rberlind Hello again,

This particular file on orders appears to be left over from the initial build, almost a year ago.

**Comment by rberlind** [comment]
Thanks.  I think there are several cases of top-level Docker files that possibly should be removed to avoid confusion.

**Comment by jasonrichardsmith** [comment]
@rberlind if there are particular repos you want to target, please open issues on those repos and then we can close them as PRs are submitted.
