### ISSUE TITLE
Inconsistencies in docker compose files?

### ISSUE THREAD

**Issue by rberlind** [microservices-demo/microservices-demo#688]
I was wondering about some inconsistencies with regard to docker compose files in some of the repositories.  In particular, I have two questions:

1) Why do the Java repositories (carts, orders, and shipping) that use zipkin have only 1 docker compose file, docker-compose-zipkin.yml, while the repositories that use Go (catalogue, user, and payment) have both that file and one called docker-compose.yml which does not include zipkin? I would expect all 6 repositories that use zipkin to include docker compose files with and without zipkin.  Perhaps this is because the Java apps need Zipkin to be running?

2) Shouldn't the docker-compose-zipkin.yml file for carts include the carts-db service?

Thanks,
Roger Berlind

**Comment by jasonrichardsmith** [comment]
@rberlind Hi, thanks for the question.

For testing purposes, we spun up a Zipkin machine to insure they connected.

**Comment by rberlind** [comment]
Thanks, Jason.  I think that answers question 1.  I suspect that the Java apps are less tolerant than the Go apps of not being able to connect to the Zipkin server.

What about question 2 about the carts docker compose file not listing carts-db?  That seems like an oversight.

**Comment by jasonrichardsmith** [comment]
carts-db is not required to test zipkin connectivity.  @rberlind

**Comment by gurushub** [comment]
I am getting the below error when CARTS service is run both through docker and maven. Running on a centos 7 env. 

com.mongodb.MongoSocketException: carts-db: Name does not resolve
carts_1   |     at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[mongodb-driver-core-3.2.2.jar!/:na]
carts_1   |     at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongodb-driver-core-3.2.2.jar!/:na]
carts_1   |     at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.2.2.jar!/:na]
carts_1   |     at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongodb-driver-core-3.2.2.jar!/:na]
carts_1   |     at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) ~[mongodb-driver-core-3.2.2.jar!/:

**Comment by edwardzjl** [comment]
> I am getting the below error when CARTS service is run both through docker and maven. Running on a centos 7 env.
> 
> com.mongodb.MongoSocketException: carts-db: Name does not resolve
> carts_1 | at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[mongodb-driver-core-3.2.2.jar!/:na]
> carts_1 | at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongodb-driver-core-3.2.2.jar!/:na]
> carts_1 | at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.2.2.jar!/:na]
> carts_1 | at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongodb-driver-core-3.2.2.jar!/:na]
> carts_1 | at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) ~[mongodb-driver-core-3.2.2.jar!/:

getting the same error
