### ISSUE TITLE
Not able to understand how all the microservices are running on the same ip

### ISSUE THREAD

**Issue by Ashok-Kumar-Venaktesh** [microservices-demo/microservices-demo#723]
I have cloned your project.  Trying to understand the communication between microservices.  Can anyone help me to understand? I tried to reach out but don't know whom to contact.  

Please expain the flow how communication between microservices happening.

**Comment by pidster** [comment]
They're not all running on the same IP.
Each service runs in a container and, depending on the orchestrator (Docker, Kubernetes, etc), is provided with its own IP.

You can use Weave Scope to visualise what happens when traffic passes through the system.

**Comment by pidster** [comment]
There's a 'sock-shop' channel on http://slack.weave.works/ if you want to ask more questions.
