### ISSUE TITLE
Remove deploy/kubernetes/complete-demo.yaml file

### ISSUE THREAD

**Issue by etiennetremel** [microservices-demo/microservices-demo#746]
As @mongrelion commented about getting rid of the complete file (see https://github.com/microservices-demo/microservices-demo/pull/731#issuecomment-320656100), I would also suggest to remove it as it confuse people and duplicate the work when making a change.

By removing it, if you apply the changes to the cluster using the following command:

```bash
kubectl apply -f deploy/kubernetes/manifests-logging
```

We will have a bunch of errors because some resources need to be applied in a specific order.

To prevent this, we can prefix each file with a number, like `10_fluentd-sa.yml`, `11_fluentd-cr.yml`, etc.

And for the namespace issue that was raised (https://github.com/microservices-demo/microservices-demo/pull/731), we can use this technique to have the namespace definition at the top: `./00_sock-shop-namespace.yaml`.

**Comment by pidster** [comment]
Please do _not_ remove complete-demo.yml. It is linked in the Kubernetes docs - we do not want to break that for all Kubernetes users.
