### ISSUE TITLE
deploy/kubernetes/manifests/payment-dep.yaml fails due to checkin f366007a2110013ddd29dc92afc8d30ada06de10

### ISSUE THREAD

**Issue by gaganapplatix** [microservices-demo/microservices-demo#753]
Not sure if this is on purpose but checkin f366007a2110013ddd29dc92afc8d30ada06de10 seems to cause the manifest of payment-dep.yaml to fail create due to requesting more resources than limit in kubernetes gke cluster.

**Comment by pidster** [comment]
Thank you @gaganapplatix. Investigating now.

**Comment by pidster** [comment]
PR here: https://github.com/microservices-demo/microservices-demo/pull/754
