### ISSUE TITLE
switch to standard metrics in front-end has broken unified dashboards

### ISSUE THREAD

**Issue by rade** [microservices-demo/microservices-demo#765]
In microservices-demo/front-end#99 we switched to what is considered to be a more standard metric(*) for reporting request counts and latencies - `http_request_duration_seconds` with a `path`. Unfortunately that has broken some unified dashboards (e.g. RED metric notebooks) that report on all the sock-shop workloads, since all other workloads are still emitting `request_duration_seconds` metrics with a `route`, and that is what the RED metric notebooks are using.

We either need to change all the other metrics, or find a way of creating the unified RED metric notebooks from multiple metrics.

(*) @jpellizzari what makes this new metric more standard than the previous one?

**Comment by dlespiau** [comment]
https://prometheus.io/docs/practices/naming/ makes them more "standard". As noted in the PR it sounds  reasonable to add support for different variations when they are used by libraries/examples/... throughout the net. We can also support `request_duration_seconds` + `route` and that may be a faster path for kubecon.

**Comment by rade** [comment]
I reckon we should follow Damien's suggestion, i.e.  support `request_duration_seconds` + `route` in the Weave Cloud dashboards and revert the change to the front-end metrics (which will unbreak the unified RED metrics notebook).

**Comment by rade** [comment]
The correct solution of course would be to change the metrics in all the other workloads to `http_request_duration_seconds`.

**Comment by dholbach** [comment]
This would be great to have fixed/deployed before KubeCon for demo purposes.

**Comment by jpellizzari** [comment]
@dholbach I plan on getting this done before the end of the week

**Comment by dholbach** [comment]
<3

**Comment by jpellizzari** [comment]
PRs:

* https://github.com/microservices-demo/carts/pull/35
* https://github.com/microservices-demo/payment/pull/35
* https://github.com/microservices-demo/user/pull/59
* https://github.com/microservices-demo/catalogue/pull/45

**Comment by jpellizzari** [comment]
Working now: https://cloud.weave.works/prom/little-meadow-46/notebook/4ca79d45-ff63-4a12-b3e5-9ccf57408c05

**Comment by dholbach** [comment]
Thanks @jpellizzari!
