### ISSUE TITLE
How to generate the log of Sock Shop or how to view the log of Sock Shop in Grafana?

### ISSUE THREAD

**Issue by XuGuanghui6688** [microservices-demo/microservices-demo#829]
I currently use the Sock Shop microservice system for academic research.
I use the Sock Shop system deployed by docker-compose, and I can open the system page in my browser.
Then enter the following command in the terminal to view the performance of each service in Grafana. This command is the monitoring file in the deployment folder.
"docker-compose -f ./deploy/docker-compose/docker-compose.monitoring.yml up -d"
But I want to view the running log of Sock Shop. I want to run the log file in the deployment folder with the following command, but something went wrong.
"docker-compose -f ./deploy/docker-compose/docker-compose.logging.yml up -d"
The error is as follows:
![image](https://user-images.githubusercontent.com/81084175/112740960-d5928780-8fb3-11eb-9f14-6ceeb8013d0b.png)

I also tried to use Loki to view the running log of Sock Shop in Grafana, but it also failed, because when I installed Loki, the port of Grafana would conflict, so how do I generate the running log of Sock Shop?

**Comment by rodrmartinez** [comment]
HI @XuGuanghui6688 , sorry for the late response. As stated in the [documentation](https://microservices-demo.github.io/deployment/docker-compose.html) to use the logging setup you have to run the following command:
`docker-compose -f deploy/docker-compose/docker-compose.yml -f deploy/docker-compose/docker-compose.logging.yml up -d`
