### ISSUE TITLE
This project is fully nonworking for minikube now!!!

### ISSUE THREAD

**Issue by someconservator** [microservices-demo/microservices-demo#830]
$ kubectl create -f deploy/kubernetes/manifests/sock-shop-ns.yaml -f deploy/kubernetes/manifests
namespace/sock-shop created
service/carts-db created
service/carts created
service/catalogue-db created
service/catalogue created
service/front-end created
service/orders-db created
service/orders created
service/payment created
service/queue-master created
service/rabbitmq created
service/session-db created
service/shipping created
service/user-db created
service/user created
Error from server (AlreadyExists): error when creating "deploy/kubernetes/manifests/loadtest-dep.yaml": namespaces "loadtest" already exists
Error from server (AlreadyExists): error when creating "deploy/kubernetes/manifests/sock-shop-ns.yaml": namespaces "sock-shop" already exists
[unable to recognize "deploy/kubernetes/manifests/carts-db-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/carts-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/catalogue-db-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/catalogue-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/front-end-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/loadtest-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/orders-db-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/orders-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/payment-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/queue-master-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/rabbitmq-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/session-db-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/shipping-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/user-db-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "deploy/kubernetes/manifests/user-dep.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"]
$ kubectl get pods --namespace="sock-shop"
No resources found in sock-shop namespace.

**Comment by swapnilbarwat** [comment]
you may find solution mentioned in this bug: #802

**Comment by rodrmartinez** [comment]
this issues has been solved by #809
