### ISSUE TITLE
Contribs Repo

### ISSUE THREAD

**Issue by elieserr** [microservices-demo/microservices-demo#833]
Currently, there are multiple deployment options that are fully outdated and built for platforms that probably are not worth maintaining.
It would be great if we support only a couple like Kubernetes and docker-compose.

The remaining deployment options could be removed from this repo and moved to a `users-contribs` repository just in case that someone has a use case for those or want to maintain it.

We should have only supported and updated deployment options.

**Comment by rodrmartinez** [comment]
Solved by #834
