### ISSUE TITLE
pr #820 is not reviewed

### ISSUE THREAD

**Issue by CsatariGergely** [microservices-demo/microservices-demo#840]
- Add labels appropriate to the issue 
- Describe the expected behaviour and the actual behaviour
  - pr #820 is review-ed, comments provided and issues fixed, pr is merged
- Describe steps to reproduce the problem
  - Create pr #820 , wait for review-s for 8 months

**Comment by elieserr** [comment]
Hi @CsatariGergely,

Thanks for your contribution, we are right now trying to update the deployment methods for the microservices demo, so we will look at the PR you just mentioned.

**Comment by rodrmartinez** [comment]
Hi @CsatariGergely , the Deployments templates on that PR are using an old apiversion, this has already been fixed on the last merge. Also I would suggest to set the port numbers in `values.yaml` and use 80 as default, then modify the templates to not add the capabilities section if a different port is used, this way it will be consistent with the other supported deployment methods

**Comment by CsatariGergely** [comment]
Thanks @rodrmartinez, @elieser1101  .
@elieser1101 please provide your comments to the pr for @shiresky 
 @rodrmartinez The pr was created last September so maybe this is the reason for using the old apiversion...

**Comment by rodrmartinez** [comment]
@CsatariGergely I made a comment in the PR. Thanks
