### ISSUE TITLE
add prometheus node exporter

### ISSUE THREAD

**Issue by elieserr** [microservices-demo/microservices-demo#864]
having node_exporter can be a simple starting point for people that are learning about Prometheus and monitoring https://github.com/prometheus/node_exporter.

- Node_exporter should be part of `deploy/kubernetes/manifests-monitoring`
- Prometheus configuration should be updated properly to target the node exporter

**Comment by elieserr** [comment]
WDYT @rodrmartinez

**Comment by rodrmartinez** [comment]
good, I will add it to the monitoring manifests

**Comment by elieserr** [comment]
I was thinking this can be handled by another contributor as a good first issue. @rodrmartinez

**Comment by giannoul** [comment]
@elieser1101 I could take a crack at it

**Comment by giannoul** [comment]
Created the PR here: https://github.com/microservices-demo/microservices-demo/pull/866
